<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run(): void
    {
        User::insert([
            [
                'role' => 'admin',
                'nip' => 123456,
                'name' => 'Admin Sistem',
                'email' => 'admin@mail.com',
                'password' => Hash::make('password'),
                'nik' => 320111,
                'status' => 'aktif',
                'department' => 'IT',
                'no_hp' => 812345678,
                'profession' => 'Programmer',
                'office' => 'Pusat',
                'grade' => 'A',
                'position' => 'Administrator',
                'jabfung' => null,
                'npwp' => 123456789,
                'norek' => 987654321,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'role' => 'user',
                'nip' => 123457,
                'name' => 'Budi Santoso',
                'email' => 'budi@mail.com',
                'password' => null,
                'nik' => 320112,
                'status' => 'aktif',
                'department' => 'Keuangan',
                'no_hp' => 812345679,
                'profession' => 'Staff',
                'office' => 'Cabang A',
                'grade' => 'B',
                'position' => 'Staff',
                'jabfung' => null,
                'npwp' => 223456789,
                'norek' => 887654321,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'role' => 'user',
                'nip' => 123458,
                'name' => 'Siti Aminah',
                'email' => null,
                'password' => null,
                'nik' => 320113,
                'status' => 'aktif',
                'department' => 'SDM',
                'no_hp' => 812345680,
                'profession' => 'HR',
                'office' => 'Pusat',
                'grade' => 'B',
                'position' => 'Staff',
                'jabfung' => null,
                'npwp' => null,
                'norek' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'role' => 'user',
                'nip' => 123459,
                'name' => 'Ahmad Fauzi',
                'email' => 'ahmad@mail.com',
                'password' => null,
                'nik' => 320114,
                'status' => 'nonaktif',
                'department' => 'Operasional',
                'no_hp' => 812345681,
                'profession' => 'Supervisor',
                'office' => 'Cabang B',
                'grade' => 'C',
                'position' => 'Supervisor',
                'jabfung' => null,
                'npwp' => 323456789,
                'norek' => 777654321,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'role' => null,
                'nip' => null,
                'name' => 'Pegawai Belum Login',
                'email' => null,
                'password' => null,
                'nik' => 320115,
                'status' => 'aktif',
                'department' => 'Umum',
                'no_hp' => null,
                'profession' => null,
                'office' => 'Pusat',
                'grade' => null,
                'position' => null,
                'jabfung' => null,
                'npwp' => null,
                'norek' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
